### PR TITLE
Add belowAsHtmlParser and aboveAsHtmlParser parsers

### LINKED ISSUE #153: Add above/belowAsHtmlParser?
Parsers to display the html output would be a nice complement to the above/belowAsCode parsers.

Here is an implementation I made:

```
belowAsHtmlParser
 extends belowAsCodeParser
 description displays html output of next particle in a code block
 cueFromId
 javascript
  get code() {
   return this.selectedParticles.filter(p => p.buildHtml).map(p => p.buildHtml()).join("\n")
  }
```

Does it make sense to include something like the above native to scroll?

I'm using the above parser to demonstrate a few other parsers I implemented at https://hub.scroll.pub/codeplaygrounds/index.html

### PR DESCRIPTION
**Pull request by btheado**
Add parsers which will display raw html of following or preceding particles.

Fixes #153.

### CODE REVIEW

**Comment by breck7** [comment]
@btheado this has proved super helpful! Thanks again. Other ideas for how to improve things?

**Comment by btheado** [comment]
I have a very fuzzy idea about having some particle surfer/explorer parser which would allow chaining of particle methods and displaying the result.

```
particleExplorer
  this parent parent next particleAt 0 1 cue
some other particle
 hello world
```

`this` would be the particle parsed under particleExplorer, so all the methods will execute relative to whereever you chose to put the particleExplorer.

The intended output of the above is `hello`.

I don't have good ideas on how or if this or something like it can be implemented. Maybe you have some ideas.

Hopefully I explained it well enough that you can tell what I'm getting at.

The idea is to be able to use scroll to document how to use particles and their methods. There seem to be a LOT of particle methods and it isn't clear how to best make use of them.

**Comment by breck7** [comment]
Ohhh, very interesting insight.

You've noticed the Particles JS/TS class already contains a microlanguage for traversing and manipulating Particles, and we could make Parsers out of that, so then someone could use Scroll to traverse/manipulate particles using an already evolved microlanguage.

This is a very good idea. The Particles JS class already contains a lot of hard won knowledge about the right words to use for working with Particles, so surfacing that into Scroll seems like a lot of return for a little bit of effort.

It's also a huge step in a really interesting direction of making Scroll more usable by the Lisp crowd. Lisps start with terms for building languages, and eventually build their way up to being able to represent data and structures that users ant to use, whereas Scroll has been done in reverse: start with getting the user's data into the perfect, minimal form, and then build up the language primitives to support that form. I've always wanted to identify the great minimum set of primitives we would need to build up Scroll in Scroll, and this would be a big step toward that without a lot of work.

**Comment by breck7** [comment]
Here's a v0 for now. Gonna play with this more this weekend. Interesting direction.

https://try.scroll.pub/#scroll%0A%20%2F%2F%20First%20define%20the%20atom%20type%20for%20particle%20methods%0A%20particleMethodAtom%0A%20%20description%20Methods%20available%20on%20Particle%20instances%0A%20%20extends%20stringAtom%0A%20%20paint%20constant.language%0A%20%20%2F%2F%20Define%20common%20Particle%20methods%20as%20enum%20options%0A%20%20enum%20cue%20content%20get%20has%20length%20index%20find%20toString%20toObject%20atoms%0A%20%0A%20%2F%2F%20Then%20define%20the%20parser%0A%20particleExplorerParser%0A%20%20description%20Walk%20through%20and%20analyze%20Particle%20methods%20and%20their%20results%0A%20%20extends%20belowAsCodeParser%0A%20%20cue%20particle%0A%20%20atoms%20cueAtom%20particleMethodAtom%0A%20%20catchAllAtomType%20stringAtom%0A%20%20example%0A%20%20%20particle%20cue%0A%20%20%20%23%20Hello%20world%0A%20%20javascript%0A%20%20%20get%20code()%20%7B%0A%20%20%20%20%20%2F%2F%20Override%20the%20code%20getter%20to%20analyze%20the%20particle%20methods%0A%20%20%20%20%20const%20selectedParticles%20%3D%20this.selectedParticles%0A%20%20%20%20%20const%20methodName%20%3D%20this.getAtom(1)%0A%20%20%20%20%20const%20inputs%20%3D%20this.atoms.slice(2)%0A%20%20%20%20%20return%20selectedParticles.map(particle%20%3D%3E%20%7B%0A%20%20%20%20%20%20%20%2F%2F%20Get%20the%20method%20result%0A%20%20%20%20%20%20%20let%20result%0A%20%20%20%20%20%20%20try%20%7B%0A%20%20%20%20%20%20%20%20%20if%20(typeof%20particle%5BmethodName%5D%20%3D%3D%3D%20'function')%0A%20%20%20%20%20%20%20%20%20%20%20result%20%3D%20particle%5BmethodName%5D(...inputs)%0A%20%20%20%20%20%20%20%20%20else%20%0A%20%20%20%20%20%20%20%20%20%20%20result%20%3D%20particle%5BmethodName%5D%0A%20%20%20%20%20%20%20%7D%20catch%20(err)%20%7B%0A%20%20%20%20%20%20%20%20%20result%20%3D%20%60Error%3A%20%24%7Berr.message%7D%60%0A%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%2F%2F%20Format%20the%20output%0A%20%20%20%20%20%20%20return%20result.toString()%0A%20%20%20%20%20%7D).join('%5Cn%5Cn')%0A%20%20%20%7D%0A%20%20%20buildHtml()%20%7Breturn%20this.code%7D%0A%20%20%20buildTxt()%20%7B%0A%20%20%20%20%20return%20this.code%0A%20%20%20%7D%0A%20%0A%20particle%20get%20weight%0A%20%2F%2F%20Person%3A%0A%20%20height%2010%0A%20%20weight%20100%0A%20


```
// First define the atom type for particle methods
particleMethodAtom
 description Methods available on Particle instances
 extends stringAtom
 paint constant.language
 // Define common Particle methods as enum options
 enum cue content get has length index find toString toObject atoms

// Then define the parser
particleExplorerParser
 description Walk through and analyze Particle methods and their results
 extends belowAsCodeParser
 cue particle
 atoms cueAtom particleMethodAtom
 catchAllAtomType stringAtom
 example
  particle cue
  # Hello world
 javascript
  get code() {
    // Override the code getter to analyze the particle methods
    const selectedParticles = this.selectedParticles
    const methodName = this.getAtom(1)
    const inputs = this.atoms.slice(2)
    return selectedParticles.map(particle => {
      // Get the method result
      let result
      try {
        if (typeof particle[methodName] === 'function')
          result = particle[methodName](...inputs)
        else 
          result = particle[methodName]
      } catch (err) {
        result = `Error: ${err.message}`
      }
      // Format the output
      return result.toString()
    }).join('\n\n')
  }
  buildHtml() {return this.code}
  buildTxt() {
    return this.code
  }

particle get weight
// Person:
 height 10
 weight 100

```

**Comment by btheado** [comment]
> I've always wanted to identify the great minimum set of primitives we would need to build up Scroll in Scroll, and this would be a big step toward that without a lot of work.

Yes, while reading the particle code I was wondering what the minimal requirements are for the system to be bootstrapped.

> Here's a v0 for now. Gonna play with this more this weekend. Interesting direction.

That was fast! Great start, very cool!

**Pull request merged**
